apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-uat
  name: nginx-uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-uat
  template:
    metadata:
      labels:
        app: nginx-uat
    spec:
      containers:
      - image: nginx
        name: nginx-uat
